# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

parameters:
  image-tag:
    type: string
    default: "current"
  workingdir:
    type: string
    default: "~/main"

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "save_hello_world_output"
          command: |
            echo "text to output here" > output.txt
      - persist_to_workspace:
          root: /tmp/workspace     # relative path to our working directory
          paths:      # file globs which will be persisted to the workspace
           - echo-output

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace # relative path to our working directory
      - run:
          name: "print_output_file"
          command: |
            cat /tmp/workspace/output.txt



# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome-workflow-zak:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - save_hello_world_output:
          requires: [welcome/run]
      - print_output_file:
          requires: [save_hello_world_output]
