version: 2.1

commands:
  print_pipeline_id:
    description: "Copy CIRCLE_WORKFLOW_ID and CIRCLE_REPOSITORY_URL to the console"
    parameters:
      WF_ID:
        type: string
        default: << CIRCLE_WORKFLOW_ID >>
      CCI_REPO_URL:
        type: string
        default: << CIRCLE_REPOSITORY_URL >>
    steps:
      - run: echo CIRCLE_WORKFLOW_ID is << parameters.WF_ID >>
      - run: echo CIRCLE_REPOSITORY_URL is << parameters.CCI_REPO_URL >>

jobs:
  print_env_var_consol_using_commands:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - print_pipeline_id

workflows:
  welcome-workflow-zak:
    jobs:
      - print_env_var_consol_using_commands